/*
 * Headers for generic DFT routines.
 *
 */

/*
 * Preprocessor defines 
 *
 */

#define DFT_MAX_POTENTIAL_POINTS 8192

/*
 * Structures
 *
 */

typedef struct lj_struct {
  REAL h, sigma, epsilon, cval;
} dft_common_lj;

typedef struct extpot {
  REAL points[DFT_MAX_POTENTIAL_POINTS];
  REAL begin;
  INT length;
  REAL step;
} dft_extpot;

typedef struct extpot_set {
  dft_extpot *x;
  dft_extpot *y;
  dft_extpot *z;
  char average;
  /* orientation of the potential */
  REAL theta0;
  REAL phi0;
  REAL x0, y0, z0; /* origin */
} dft_extpot_set;

/*
 * Prototypes (auto generated by Makefile).
 *
 */

#define EXPORT
